#!/usr/bin/env python3
"""Render the distribution manifests for a berth release.

The release workflow publishes one archive per platform plus a checksums.txt
file. This script reads that file and writes the three package-manager
manifests from it, so a release never needs a hand-copied sha256.

Usage:
    python distribution/render.py --tag v0.2.0                 # fetch checksums from the release
    python distribution/render.py --tag v0.2.0 --checksums path/to/checksums.txt
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = "Mrjwj34/berth"
DESCRIPTION = "Fast, daemonless local workspaces for parallel coding agents"
HOMEPAGE = f"https://github.com/{REPO}"
LICENSE = "MIT"
DOCS = "https://mrjwj34.github.io/berth/"
TAP = "Mrjwj34/tap"
BUCKET_REPO = "Mrjwj34/scoop-bucket"

PLATFORMS = {
    "darwin_amd64": ("darwin", "x86_64", "tar.gz"),
    "darwin_arm64": ("darwin", "arm64", "tar.gz"),
    "linux_amd64": ("linux", "x86_64", "tar.gz"),
    "linux_arm64": ("linux", "arm64", "tar.gz"),
    "windows_amd64": ("windows", "x64", "zip"),
    "windows_arm64": ("windows", "arm64", "zip"),
}


def die(message: str) -> "None":
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def fetch_checksums(tag: str) -> str:
    url = f"{HOMEPAGE}/releases/download/{tag}/checksums.txt"
    print(f"fetching {url}")
    with urllib.request.urlopen(url, timeout=60) as response:  # noqa: S310 - fixed https URL
        return response.read().decode("utf-8")


def parse_checksums(text: str, version: str) -> dict[str, str]:
    """Map platform key -> sha256, verifying every expected asset is present."""
    by_name: dict[str, str] = {}
    for line in text.splitlines():
        parts = line.split()
        if len(parts) != 2:
            continue
        digest, name = parts[0], parts[1].lstrip("*")
        by_name[name] = digest.lower()

    found: dict[str, str] = {}
    missing: list[str] = []
    for key, (goos, _, ext) in PLATFORMS.items():
        asset = f"berth_{version}_{goos}_{key.split('_')[1]}.{ext}"
        if asset not in by_name:
            missing.append(asset)
            continue
        digest = by_name[asset]
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            die(f"{asset}: not a sha256 digest: {digest!r}")
        found[key] = digest

    if missing:
        die("release is missing expected assets: " + ", ".join(missing))
    return found


def asset_url(tag: str, goos: str, arch: str, ext: str) -> str:
    return f"{HOMEPAGE}/releases/download/{tag}/berth_{tag.lstrip('v')}_{goos}_{arch}.{ext}"


def render_homebrew(version: str, tag: str, sums: dict[str, str]) -> str:
    def block(os_name: str, cpu_arm: str, cpu_intel: str) -> str:
        return f"""    if Hardware::CPU.arm?
      url "{asset_url(tag, os_name, 'arm64', 'tar.gz')}"
      sha256 "{sums[f'{os_name}_arm64']}"
    else
      url "{asset_url(tag, os_name, 'amd64', 'tar.gz')}"
      sha256 "{sums[f'{os_name}_amd64']}"
    end"""

    return f"""# Generated by distribution/render.py -- do not edit by hand.
class Berth < Formula
  desc "{DESCRIPTION}"
  homepage "{HOMEPAGE}"
  version "{version}"
  license "{LICENSE}"

  on_macos do
{block('darwin', 'arm64', 'amd64')}
  end

  on_linux do
{block('linux', 'arm64', 'amd64')}
  end

  livecheck do
    url "{HOMEPAGE}"
    strategy :github_latest
  end

  def install
    bin.install "berth"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/berth version")
  end
end
"""


def render_scoop(version: str, tag: str, sums: dict[str, str]) -> str:
    manifest = {
        "version": version,
        "description": DESCRIPTION,
        "homepage": HOMEPAGE,
        "license": LICENSE,
        "architecture": {
            "64bit": {
                "url": asset_url(tag, "windows", "amd64", "zip"),
                "hash": sums["windows_amd64"],
            },
            "arm64": {
                "url": asset_url(tag, "windows", "arm64", "zip"),
                "hash": sums["windows_arm64"],
            },
        },
        "bin": "berth.exe",
        "checkver": {"github": HOMEPAGE},
        "autoupdate": {
            "architecture": {
                "64bit": {
                    "url": f"{HOMEPAGE}/releases/download/v$version/berth_$version_windows_amd64.zip"
                },
                "arm64": {
                    "url": f"{HOMEPAGE}/releases/download/v$version/berth_$version_windows_arm64.zip"
                },
            }
        },
    }
    return json.dumps(manifest, indent=4) + "\n"


def render_winget(version: str, tag: str, sums: dict[str, str]) -> dict[str, str]:
    installer = {
        "PackageIdentifier": "Mrjwj34.berth",
        "PackageVersion": version,
        "InstallerType": "zip",
        "NestedInstallerType": "portable",
        "NestedInstallerFiles": [
            {"RelativeFilePath": "berth.exe", "PortableCommandAlias": "berth"}
        ],
        "Installers": [
            {
                "Architecture": "x64",
                "InstallerUrl": asset_url(tag, "windows", "amd64", "zip"),
                "InstallerSha256": sums["windows_amd64"],
            },
            {
                "Architecture": "arm64",
                "InstallerUrl": asset_url(tag, "windows", "arm64", "zip"),
                "InstallerSha256": sums["windows_arm64"],
            },
        ],
        "ManifestType": "installer",
        "ManifestVersion": "1.6.0",
    }
    locale = {
        "PackageIdentifier": "Mrjwj34.berth",
        "PackageVersion": version,
        "PackageLocale": "en-US",
        "Publisher": "Mrjwj34",
        "PublisherUrl": "https://github.com/Mrjwj34",
        "PackageName": "berth",
        "PackageUrl": HOMEPAGE,
        "License": LICENSE,
        "LicenseUrl": f"{HOMEPAGE}/blob/main/LICENSE",
        "ShortDescription": DESCRIPTION,
        "Description": (
            "berth provisions lightweight, isolated local workspaces for parallel agent "
            "programming, combining Git worktrees, private data directories, dynamic port "
            "assignment and supervised processes without virtual machine overhead."
        ),
        "Moniker": "berth",
        "Tags": [
            "ai-agents",
            "cli",
            "coding-agents",
            "developer-tools",
            "dev-environment",
            "git-worktree",
            "go",
        ],
        "ReleaseNotesUrl": f"{HOMEPAGE}/releases/tag/{tag}",
        "ManifestType": "defaultLocale",
        "ManifestVersion": "1.6.0",
    }
    version_manifest = {
        "PackageIdentifier": "Mrjwj34.berth",
        "PackageVersion": version,
        "DefaultLocale": "en-US",
        "ManifestType": "version",
        "ManifestVersion": "1.6.0",
    }
    return {
        "Mrjwj34.berth.yaml": yaml_dump(version_manifest),
        "Mrjwj34.berth.installer.yaml": yaml_dump(installer),
        "Mrjwj34.berth.locale.en-US.yaml": yaml_dump(locale),
    }


def yaml_dump(data: object, indent: int = 0) -> str:
    """Minimal YAML writer: the manifests only use mappings, lists and scalars."""
    pad = " " * indent
    if isinstance(data, dict):
        out = []
        for key, value in data.items():
            if isinstance(value, (dict, list)) and value:
                out.append(f"{pad}{key}:")
                out.append(yaml_dump(value, indent + 2))
            elif isinstance(value, (dict, list)):
                out.append(f"{pad}{key}: {'{}' if isinstance(value, dict) else '[]'}")
            else:
                out.append(f"{pad}{key}: {scalar(value)}")
        return "\n".join(out) + ("\n" if indent == 0 else "")
    if isinstance(data, list):
        out = []
        for value in data:
            if isinstance(value, dict):
                rendered = yaml_dump(value, indent + 2).rstrip("\n").split("\n")
                first = rendered[0].lstrip()
                out.append(f"{pad}- {first}")
                out.extend(rendered[1:])
            else:
                out.append(f"{pad}- {scalar(value)}")
        return "\n".join(out) + ("\n" if indent == 0 else "")
    return f"{pad}{scalar(data)}\n"


def scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        escaped = value.replace('"', '\\"')
        return f'"{escaped}"'
    return str(value)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", required=True, help="release tag, e.g. v0.2.0")
    parser.add_argument("--checksums", help="local checksums.txt instead of fetching the release")
    parser.add_argument(
        "--out", default="distribution", help="output root (default: distribution)"
    )
    args = parser.parse_args()

    tag = args.tag
    version = tag.lstrip("v")
    raw = Path(args.checksums).read_text() if args.checksums else fetch_checksums(tag)
    sums = parse_checksums(raw, version)
    print(f"verified {len(sums)} assets for {tag}")

    out = Path(args.out)
    targets = {
        out / "homebrew" / "berth.rb": render_homebrew(version, tag, sums),
        out / "scoop" / "berth.json": render_scoop(version, tag, sums),
    }
    for name, content in render_winget(version, tag, sums).items():
        targets[out / "winget" / name] = content

    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}")

    print(f"\nHomebrew: brew install {TAP}/berth")
    print(f"Scoop:    scoop bucket add berth {HOMEPAGE.replace('Mrjwj34/berth', BUCKET_REPO)} && scoop install berth")
    print("winget:   submit distribution/winget to microsoft/winget-pkgs")


if __name__ == "__main__":
    main()
