#!/usr/bin/env python3
"""Assemble the validation report from the raw reports committed next to it.

Usage:
  python tests/validation/summarise.py docs/validation/report-*.json \
      --out docs/validation/report.md

Every number in the generated report comes from a JSON file that is committed
beside it, so the summary can always be regenerated instead of trusted.
"""

from __future__ import annotations

import argparse
import json
import platform
from pathlib import Path


def os_name(report: dict) -> str:
    text = report.get("environment", {}).get("platform", "") or platform.platform()
    for needle, name in (("Windows", "Windows"), ("Darwin", "macOS"), ("mac", "macOS"), ("Linux", "Linux")):
        if needle in text:
            return name
    return "unknown"


def label(report: dict) -> str:
    return f"{report['mode']} on {os_name(report)}"


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join("" if cell is None else str(cell) for cell in row) + " |")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("reports", nargs="+")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    runs = []
    for path in args.reports:
        file = Path(path)
        report = json.loads(file.read_text(encoding="utf-8"))
        # Several runs share a label (native on Windows, for instance), so the
        # report file names the column. The raw JSON is committed beside this
        # file, so a column always maps back to its evidence.
        stem = file.stem.replace("report-", "")
        runs.append((f"{label(report)} · {stem}", file.name, report))

    lines: list[str] = ["# Validation results", ""]
    lines += [
        "Generated by `tests/validation/summarise.py` from the raw reports in this",
        "directory. Each cell counts **business assertions**, not readiness probes.",
        "",
        "## Environment",
        "",
    ]
    rows = []
    for name, file, report in runs:
        env = report.get("environment", {})
        rows.append([
            name,
            f"`{env.get('platform', '-')}`",
            report.get("mode", "-"),
            f"`{env.get('image') or '-'}`",
            f"`{env.get('engine') or '-'}`",
            env.get("cpu_count", "-"),
            f"`{env.get('python', '-')}`",
            f"`{file}`",
        ])
    lines += table(["run (column label = run name · report stem)", "platform", "runtime", "image",
                    "engine", "cpus", "python", "raw report"], rows)
    lines.append("")

    lines += ["## Correctness", ""]
    levels = sorted({level for _, _, report in runs for level in report.get("levels", {})})
    rows = []
    for level in levels:
        row = [f"`{level}`"]
        for name, _file, report in runs:
            data = report.get("levels", {}).get(level)
            if not data:
                row.append("not run")
                continue
            checks = data.get("checks", [])
            passed = sum(1 for check in checks if check["ok"])
            if data.get("ok"):
                row.append(f"{passed}/{len(checks)} pass")
            else:
                row.append(f"**FAILED** ({passed}/{len(checks)})")
        rows.append(row)
    lines += table(["level"] + [name for name, _file, _report in runs], rows)
    lines.append("")

    lines += ["## Performance", ""]
    for level in levels:
        lines += [f"### `{level}`", ""]
        metrics: list[str] = []
        for _name, _file, report in runs:
            data = report.get("levels", {}).get(level, {})
            for section in ("timings_ms", "resources"):
                for key in data.get(section, {}):
                    if key not in metrics:
                        metrics.append(key)
        if not metrics:
            lines += ["_no measurements recorded_", ""]
            continue
        rows = []
        for metric in metrics:
            row = [f"`{metric}`"]
            for _name, _file, report in runs:
                data = report.get("levels", {}).get(level, {})
                value = data.get("timings_ms", {}).get(metric)
                if value is None:
                    value = data.get("resources", {}).get(metric)
                row.append("-" if value is None else value)
            rows.append(row)
        lines += table(["metric"] + [name for name, _file, _report in runs], rows)
        lines.append("")

    defects: list[tuple[str, str]] = []
    for name, _file, report in runs:
        for level, data in report.get("levels", {}).items():
            for note in data.get("notes", []):
                if "DEFECT" in note or "RELEASE FAILED" in note or "SKIPPED" in note:
                    defects.append((f"{name} / {level}", note))
    lines += ["## Findings from the runs", ""]
    if defects:
        for where, note in defects:
            lines += [f"- **{where}** — {note}"]
    else:
        lines += ["- No defect, skip or release failure was recorded."]
    lines += ["", "## Limitations", ""]
    lines += [
        "- The container runtime was exercised on Linux runners with one container per",
        "  workspace, because the developer machine that produced the native reports has no",
        "  container engine installed. Container numbers and native numbers therefore come",
        "  from different machines and are not directly comparable.",
        "- Level 4 validates a private business repository in local native runs and a public",
        "  project in CI. The same code path runs both; only the spec file differs, and CI",
        "  never touches the private repository.",
        "- Level 3 uses SQLite reached over TCP through a dedicated service process, not a",
        "  PostgreSQL server: none of the available runtimes can host one on the native path.",
        "- Cycles spent building project dependencies (module downloads, `pnpm install`) are",
        "  included in the numbers and dominate the setup hook timings on a cold cache.",
        "",
    ]
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out} from {len(runs)} reports")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
